CREATE DATABASE TrippyApplication;

CREATE TABLE IF NOT EXISTS public.types
(
    type_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    type_name character varying(50) COLLATE pg_catalog."default",
    CONSTRAINT types_pkey PRIMARY KEY (type_id)
);
CREATE TABLE IF NOT EXISTS public.cities
(
    city_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    city_name character varying(50) COLLATE pg_catalog."default",
    CONSTRAINT city_pkey PRIMARY KEY (city_id)
);
CREATE TABLE IF NOT EXISTS public.venues
(
    venue_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
	type_id integer NOT NULL,
	city_id integer NOT NULL,
    venue_name character varying(50) COLLATE pg_catalog."default",
	address character varying(100) COLLATE pg_catalog."default",
	rating float(1),
	reviewsCount integer,
    CONSTRAINT venue_pkey PRIMARY KEY (venue_id),
	CONSTRAINT venues_type_id_fkey FOREIGN KEY (type_id)
        REFERENCES public.types (type_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT venues_city_id_fkey FOREIGN KEY (city_id)
        REFERENCES public.cities (city_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
);
CREATE TABLE IF NOT EXISTS public.users
(
    user_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
	username character varying(50) NOT NULL COLLATE pg_catalog."default",
	city_id integer NOT NULL,
    email character varying(50) NOT NULL COLLATE pg_catalog."default",
	joinDate date,
    CONSTRAINT user_pkey PRIMARY KEY (user_id),
	CONSTRAINT users_city_id_fkey FOREIGN KEY (city_id)
        REFERENCES public.cities (city_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
);
CREATE TABLE IF NOT EXISTS public.reviews
(
    review_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
	user_id integer NOT NULL,
	venue_id integer NOT NULL,
	creationDate date,
	rating float(1) NOT NULL,
	text character varying(1000) COLLATE pg_catalog."default",
    CONSTRAINT review_pkey PRIMARY KEY (review_id),
	CONSTRAINT reviews_user_id_fkey FOREIGN KEY (user_id)
        REFERENCES public.users (user_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT reviews_venue_id_fkey FOREIGN KEY (venue_id)
        REFERENCES public.venues (venue_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
);